- name: Install packages
  xbps: name={{ item }} state=present update_cache=yes
  with_items:
    # alternative XBPS repositories
    - void-repo-multilib
    - void-repo-nonfree
    - void-repo-multilib-nonfree

    # system packages
    - socklog-void
    - chrony
    - pipewire
    - wireplumber
    - elogind
    - polkit
    - tlp
    - NetworkManager
    - dbus
    - mesa-dri
    - mesa-dri-32bit
    - vulkan-loader
    - mesa-vulkan-radeon
    - mesa-vaapi
    - mesa-vdpau
    - alsa-pipewire
    - bluez
    - libspa-bluetooth
    - cups

    # misc
    - btop
    - curl
    - git
    - vim
    - neovim
    - lsd
    - topgrade
    - yadm
    - nodejs
    - docker
    - docker-compose
    - go
    - rust
    - cargo
    - ripgrep
    - unzip

    # python
    - python3
    - python3-pip
    - python3-virtualenv
    - python3-pipx

    # fonts
    - xorg-fonts
    - noto-fonts-ttf
    - noto-fonts-ttf-extra
    - noto-fonts-emoji
    - noto-fonts-cjk
    - google-fonts-ttf
    - nerd-fonts

- name: Remove packages
  xbps: name={{ item }} state=absent recurse=yes
  with_items:
    - pulseaudio
    - pavucontrol
    - vscode
    - bpytop

- name: Install 'git-split-diffs' npm package
  community.general.npm:
    name: git-split-diffs
    global: true

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - com.discordapp.Discord
    - com.github.tchx84.Flatseal
    - com.saivert.pwvucontrol
    - com.sindresorhus.Caprine
    - io.freetubeapp.FreeTube
    - org.signal.Signal

- name: Remove flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: absent
  with_items:
    - io.github.spacingbat3.webcord

- name: Create /opt/vscode directory
  file:
    path: /opt/vscode
    state: directory

- name: Download and extract Visual Studio Code
  unarchive:
    src: https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
    dest: /opt/vscode
    remote_src: yes
    creates: /opt/vscode/code
    extra_opts: --strip-components=1

- name: Link Visual Studio Code binary
  file:
    src: /opt/vscode/code
    dest: /usr/local/bin/code
    state: link

- name: Copy .desktop files for Visual Studio Code
  copy:
    src: "{{ item }}"
    dest: /usr/share/applications/
  with_items:
    - vscode.desktop
    - vscode-url-handler.desktop

